<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByWord($word)
    {

        $qb = $this->createQueryBuilder('u')
            ->where('u.name LIKE :word')
            ->setParameter('word', '%'.$word.'%')
            ->getQuery();
        return $qb->execute();
    }
}
